
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php else : ?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif; ?>
        <p><?= /* @escapeNotVerified */
            __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $order = $objectManager->create('\Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
    $amount = round($order->getGrandTotal(), 3);
    $formattedPrice = $priceHelper->currency($amount, true, false);
    $request = $objectManager->get('Magento\Framework\App\Request\Http');
    $params = $request->getParams();
    ?>
    <?php
    if ($params) {
        $paymentID = isset($params['paymentid']) ? $params['paymentid'] : '';
        $presult = isset($params['result']) ? $params['result'] : '';
        $postdate = isset($params['postdate']) ? $params['postdate'] : '';
        $tranid = isset($params['tranid']) ? $params['tranid'] : '';
        $auth = isset($params['auth']) ? $params['auth'] : '';
        $ref = isset($params['ref']) ? $params['ref'] : '';
        $trackid = isset($params['trackid']) ? $params['trackid'] : '';

        $message = '<h2>KNET Payment Details:</h2><br />';
        $message .= '<div><strong>PaymentID: </strong>' . $paymentID . "</div><br>";
        $message .= '<div><strong>Amount: </strong>' . $formattedPrice . "</div><br>";
        $message .= '<div><strong>Result: </strong>' . $presult . "</div><br>";
        $message .= '<div><strong>PostDate: </strong>' . $postdate . "</div><br>";
        $message .= '<div><strong>TranID: </strong>' . $tranid . "</div><br>";
        $message .= '<div><strong>Auth: </strong>' . $auth . "</div><br>";
        $message .= '<div><strong>Ref: </strong>' . $ref . "</div><br>";
        $message .= '<div><strong>TrackID: </strong>' . $trackid . "</div><br>";
        $message .= '<div><strong>Time: </strong>' . date('H:i:s') . "</div><br>";

        echo $message;
    }
    ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */
            $storeManager->getStore()->getBaseUrl() ?>"><span><?= /* @escapeNotVerified */
                    __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
