<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 * @since 2.3.0
 * Modified by X-MAGE2
 */
?>
<script>
    require([
        'jquery',
        'mage/template',
        'prototype'
    ], function(jQuery, mageTemplate){

        setSettings = function(urlTemplate, entityTypeElement, attributeIdElement) {
            var url;

            if (!jQuery('#selectattribute_form').valid()) {
                return false;
            }
            entityTypeElement = $F(entityTypeElement);
            attributeIdElement = $F(attributeIdElement);

            url = mageTemplate(urlTemplate, {
                data: {
                    'entity_type_code': entityTypeElement,
                    'attribute_id': attributeIdElement
                }
            });

            setLocation(url);
        };
    });
</script>
