<?php
/**
 * Webkul Software.
 *
 * PHP version 7.0+
 *
 * @category  Webkul
 * @package   Webkul_MobikulCore
 * @author    Webkul <support@webkul.com>
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html ASL Licence
 * @link      https://store.webkul.com/license.html
 */?>
<?php if ($block->isAr()): ?>
    <?php $productArUrl = $block->getArProductData(); ?>
        <a href="<?= $productArUrl; ?>" rel="ar">
            <img 
                class="ar-img" 
                src="<?= $block->getViewFileUrl('Webkul_MobikulCore::images/transparent.png'); ?>" 
            />
        </a>
<?php endif; ?>
