<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Customize by x-mage2 to add custom attributes form
 */

// @codingStandardsIgnoreFile

/**
 * USAGE:
 *
 * Simple:
 *
 * <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
 * ->setDate($block->getCustomer()->getDob())
 * ->toHtml() ?>
 *
 * For checkout/onepage/billing.phtml:
 *
 * <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
 * ->setDate($block->getCustomer()->getDob())
 * ->setFieldIdFormat('billing:%s')
 * ->setFieldNameFormat('billing[%s]')
 * ->toHtml() ?>
 *
 * NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
 * Alternatively we could calculate widths automatically using block input parameters.
 */
?>
<?php
$attribute = $block->getAttribute();
$attributeCode = $block->getAttributeCode();
$isRequired = $block->isRequired();
$attributeLabel = $attribute->getStoreLabel() != null ? $attribute->getStoreLabel() : $attribute->getFrontendLabel();
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div
    class="field <?php echo $attributeCode; ?> <?php echo $isRequired == 1 ? 'required' : '' ?>">
    <label for="<?php echo $attributeCode ?>" class="label"><span><?php /* @escapeNotVerified */
            echo $attributeLabel; ?></span></label>

    <div class="control customer-dob">

                <?php echo $block->getFieldHtml(); ?>
                <?php if ($_message = $block->getAdditionalDescription()) : ?>
                    <div class="note"><?php /* @escapeNotVerified */
                        echo $_message; ?></div>
                <?php endif; ?>

    </div>
</div>