<?php

namespace Zkood\AddBrandOptions\Controller\Index;

class index extends \Magento\Framework\App\Action\Action
{
    protected $_eavSetupFactory;
    protected $_storeManager;
    protected $_attributeFactory;
    /**
     * @var \Magento\Eav\Model\Config
     */
    private $eavConfig;

    public function __construct(
        \Magento\Eav\Setup\EavSetupFactory $eavSetupFactory,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Catalog\Model\ResourceModel\Eav\Attribute $attributeFactory,
        \Magento\Eav\Model\Config $eavConfig,
        \Magento\Framework\App\Action\Context $context
    )
    {
        $this->_eavSetupFactory = $eavSetupFactory;
        $this->_storeManager = $storeManager;
        $this->_attributeFactory = $attributeFactory;
        $this->eavConfig = $eavConfig;
        parent::__construct($context);
    }

    public function execute()
    {
        $dropdown = array("21st Century",
            "3 Chenes",
            "LXR Biotech LLC.",
            "H.Lundbeck&Co A/S",
            "Pacific Naturals U.S.A",
            "Hexal AG",
            "Kuwait Saudi Pharma",
            "Biohit -Finland",
            "Temmler Pharma - Germany",
            "Country Life",
            "Jamjoom Pharma.",
            "Pobiotical S.P.A",
            "Smith Kline Beecham",
            "NTC s.r.l - Italy",
            "Global Health Trax Inc.",
            "Dr. Scheffler",
            "Activlab",
            "Novo Nordisk",
            "Allergan Pharmaceuticals",
            "Herb Pharma",
            "Julphar",
            "Adrien",
            "Advancis",
            "Bayer Consumer Care Ltd.",
            "Oman Pharma. Zynova",
            "WYETH",
            "Schering",
            "Dr.Madaus & Co.",
            "Amgen Europe B.V.",
            "TABUK",
            "AL MIRALL PRODESFARMA",
            "Hei Long Jiang Pharm.Co.Ltd.",
            "Searle Pharmaceuticals",
            "Meda Pharma Germany",
            "M.S.D.",
            "Laboratorios Tegor S.L",
            "Mega Pharma",
            "Alfa Manufacturing LLC.,USA",
            "Livealth Biopharma Pvt.Ltd.",
            "Apotex INC.",
            "Epitech Group",
            "Vitarmonyl Laboratoires",
            "Istituto Ganassini Italy",
            "National Pharma",
            "BELL SONS",
            "Alternative Medicines Ltd.",
            "Pharmacy Laboratories S.C.",
            "AVENTIS PHARMA",
            "Leosons -USA",
            "Glaxo SmithKline Export Ltd.",
            "D&E Nutraceuticals - USA",
            "Tosc International",
            "EAS",
            "Novartis",
            "ORGANON",
            "MEDINOVA LIMITED",
            "Amoun Pharma.Co. Egypt",
            "Cryotherapy Products Inc.U.S.A",
            "Bios Line S.P.A -Italy",
            "BIMBI",
            "Biogame Limited",
            "Servier Lab",
            "Arches Natural Products.U.S.A",
            "PFIZER CORP",
            "Bausch & Lomb",
            "Inventis S.A.",
            "Tyco Healthcare",
            "AstraZeneca, Sweden",
            "Atorlip",
            "Boehringer Ingelheim",
            "Avalon",
            "Bayer",
            "Avizor",
            "Leung Kai Fook",
            "Welex Lab. India",
            "Himalaya Drug Company",
            "ALCON",
            "RIYADH PHARMA",
            "Sandoz",
            "Marcyrl Pharmaceuticals Co.",
            "Mepha Ltd",
            "Baricol Bariatrics-Germany",
            "Roha Arzneimittel Gmb H.",
            "Novadiet S.A",
            "Galderma Labora.",
            "Mundi Pharma AG",
            "Duphar B.V.",
            "Fresh Living Inc. USA",
            "Bio Nike",
            "F.Trenka",
            "Biocol Lab - Portugal",
            "Biocyte Lab.France",
            "Laboratoires Biofar - France",
            "FERRING PHARMACEUTICALS",
            "American Creations",
            "Laboratoires Thea -France",
            "AMO",
            "Sooft Italiya S.P.A",
            "Reckitt Benckiser",
            "Roche Pharma",
            "Glamorous",
            "Chiesi Farmaceutici",
            "Biopharma - Egypt",
            "Sanofi Aventis Consumer",
            "Lab.OM",
            "Taiba Clinic",
            "Bronson Lab.",
            "Bronson-Al Thouq",
            "ABBOTT(KNOLL)",
            "Nutrition Formulators",
            "Laboratoire Des Granions",
            "Laboratoires Surveal Sprl.",
            "Cosmoactive Co.-Turkey",
            "ROWA PHARMACEUTICALS LIMITED",
            "Vitabiotics",
            "IPCA Laboratories Ltd.",
            "Thornton & Ross Ltd",
            "The Applied Company For Therap",
            "EvaPharma",
            "Arafarma GROUP,S.A.",
            "Fabrik Montavit-Austria",
            "Spimaco",
            "Laboratories Serono S.A.",
            "Gelita Health Gmbh-Germany",
            "Pharmacia Upjohn(Kabi)",
            "Prestige Brands Int.INC",
            "Insight Pharmaceuticals Crop.",
            "Vox Nutrition Inc.",
            "Eli-Lilly & Co.",
            "Cinfa",
            "The United Pharma Mfg. Co",
            "Erbex",
            "U.C.B.",
            "Shedir Pharma Srl.",
            "Dar Al-Dawa Co.",
            "Celsis Farmaceutica",
            "Natural Product Co.",
            "Eipico",
            "Equilibre Attitude",
            "Merck",
            "MERZ",
            "PK Benelux Bv",
            "Biopolymer",
            "SERONO PHARMA",
            "Pierre Fabre Dermo, France",
            "A.H.Cox",
            "Algorithm",
            "Laboratoires Bailleul S.A.",
            "LEO PHARMACEUTICALS PRODUCTS L",
            "JANSSEN",
            "PHARMACIA",
            "Biofaktor Sp.- Poland",
            "THE MENTHOLATUM COMPANY LTD.",
            "Denk Pharma Gmbh.-Germany",
            "D.D.D. LIMITED",
            "H&N Co.,",
            "Pk Peters Krizman Ag",
            "Valeant Pharma.",
            "Guergi S.r.o. Ltd.",
            "Ferrer International S.A.",
            "Deva",
            "Memphis Co.",
            "Dexamed",
            "You Medical Nederland",
            "Takeda",
            "Pharma Science INC.",
            "General Healthcare Ltd.",
            "SCHERING AG",
            "Healthaid",
            "SANOFI",
            "F. Hoffmann La Roche",
            "Pharma Global",
            "Lama Pharmacy",
            "Dr.Vitamin",
            "Dream Products - USA",
            "Ducray",
            "Faes Farma - Spain",
            "EGO Pharma.Pvt.Ltd.Australia",
            "Sankyo Pharma GmbH",
            "Pierre Fabre Medicament",
            "DR. WILD",
            "Al Abyar-New Items",
            "Tillotts Pharma Ag.",
            "Euro OTC Pharma",
            "Erevil",
            "Mar-Farma Milano - Italy",
            "Sose Pharm",
            "Evia Medical Technologies",
            "Janssen Pharma.",
            "Barnaux",
            "A-MENARINI",
            "13th Protein Import AB-Sweden",
            "Benostan Laboratories Greece",
            "Novartis Consumer",
            "Vifor",
            "Ferticode",
            "Dcmg Laboratoires",
            "Fertypharm, S.L.",
            "Care Pharmaceuticals Ltd",
            "Fit 4 Life Co. USA",
            "Pharmalife",
            "Prosan International B.V",
            "Novax Pharma-France",
            "Omisan Farmaceuici",
            "LG Life Seiences Ltd. Korea",
            "Nature Pharmaceuticals",
            "IBSA",
            "Neobourne Pharma",
            "Cfpharma Ltd.-Italy",
            "G.Pohl - Boskamp Gmbh Co.KG.",
            "Alcon Cusi SA",
            "Liptis Pharmaceuticals",
            "PHARMATON",
            "Pharma-Zentrale GmbH - Germany",
            "Global Pharma",
            "PHARCO PHARMACEUTICALS",
            "KARL ENGELHARD",
            "Nikko Yakuhin",
            "Laboratoire C.C.D-France",
            "Cilag",
            "Haddrell's",
            "Health n Nature USA",
            "Health RX",
            "Puralife L.L.C-USA",
            "Apipharma Ltd",
            "Pharmamed d.o.o. - Bosnia",
            "Tulimed Pharma-Switzerland",
            "Hikma Pharmaceuticals",
            "Laboratorio Edol",
            "Aushadhi Wellness Pvt.Ltd.",
            "Earth's Creation -USA",
            "LCA Pharma.France",
            "Ursa Pharma",
            "Ichill Beverages Inc.",
            "Laboratories Innotech Int.",
            "Imedeen",
            "Ginco International",
            "Oxpharm Ltd.",
            "Vefailac san",
            "Vigapharma",
            "United Pharmaceuticals",
            "Cardinova",
            "Acino Pharma AG.",
            "Saudi Arabian Japan.Pharmaceut",
            "Ningbo Foreign Economic Trd.Cp",
            "Smart Science Lab.",
            "Joswe Medical Co.",
            "Goyeria",
            "Aimil Pharmaceuticals - India",
            "Meditec International",
            "Puralife Best Remedy",
            "Kal",
            "Smart health",
            "Trommsdorff",
            "Aspen",
            "Gricar",
            "Menarini International",
            "Distripharma Canada",
            "Abbott Laboratories S.A",
            "Bristol Myers",
            "Konicare",
            "Kordel's",
            "Lainco . sa",
            "Lamberts Health Care U.K",
            "Bushu Pharmaceuticals Ltd.",
            "Laxido",
            "Len Fa Medical",
            "Shijiazhuang Yiling Pharma",
            "ICN",
            "Pharmaceutical Soln.Ind.",
            "Four Seas.",
            "All Vendors",
            "Yamanouchi",
            "Jarallah Pharmacy",
            "Laboratories Lysaskin-France",
            "Oftal Pharma - Itlay",
            "Power Health Products Ltd.",
            "Martinez",
            "Schwitz Biotech",
            "Mar Farma Srl.",
            "Alfa Vitamins Lab-Noor",
            "Omicron Pharmaceuticals",
            "Mentholatum Co.",
            "MeroMatrix",
            "Nutrition Formula-Well Green",
            "Eisai Research Lab.",
            "Derol",
            "Solobiotics",
            "MGC Nutrition",
            "Seoul Cosmetics Co.,Ltd-Korea",
            "Medical Union Pharma",
            "Mom Enterprises,Inc",
            "Norgine",
            "Vitamec",
            "Sun Pab Health Ltd.",
            "Prestiage Brands Ltd.",
            "Al-Taqaddom Pharmaceutical",
            "Labatec Pharma Swiss",
            "3C Pharma",
            "Natures Bounty",
            "Wockhardt Limited - India",
            "Nasaleze",
            "Nature Oils",
            "Italdevice srl -Italy",
            "Nectar Royal",
            "Neopharma",
            "E.Merck",
            "Mc Neil Nutritionals",
            "Solgar",
            "HRA Pharma - France",
            "Pharma Medico Denmark",
            "Nurofen",
            "Farmaderbe",
            "Yslab-France",
            "Schulke&Mayr",
            "Olexa",
            "S.Arabian Japanese Pharm.Co",
            "S.Arabian Japanese",
            "Vianex SA",
            "Biofact-Malasiya",
            "BOOTS HEALTHCARE INTERNATIONAL",
            "Sinsin Pharm",
            "Turkuaz Co. Turkey",
            "Outiblock",
            "Amman Pharm.Industries",
            "Otosan",
            "Remedica Ltd.",
            "Pure Health",
            "Puritan's Pride",
            "Saja Pharma.Jeddah S.Arabia",
            "ALTANA PHARMA AG",
            "Paradox Omega Oil Ltd.",
            "Omega Pharma",
            "Pclq Europe",
            "Pclq Europe-P.Life",
            "Davinci Team",
            "Laboratories Ineldea",
            "Euro-Pharma Int.Canada",
            "PentaCare",
            "Perfect Life",
            "SOLVAY PHARMA",
            "ARTSANA-ITALY",
            "Ferring AB",
            "PIGEON",
            "Ambix Laboratories",
            "Silva Medica -Italy",
            "Chemical Ind.D",
            "Da Jung Ltd.",
            "Jazeera Pharm.Ind",
            "Natur Produckt Pharma -Poland",
            "Prime",
            "Wyeth Ayrest Inc.",
            "Aesculapius",
            "Humarian Research Lab,LLc.",
            "Sildeha Pharma - Italy",
            "Advance Pharma - Germany",
            "Bifodan A/S - Denmark",
            "Kendy Pharma Ltd.",
            "Bayan pharmacy",
            "Pharmatitan - Italy",
            "Sigma Tau Italy",
            "Grunenthal",
            "Purelogicol International Ltd.",
            "Axcan Pharma USA",
            "Zenta Healthcare Pvt.Ltd.India",
            "Ransom Naturals LTD",
            "Rainbow Light Nut.-USA",
            "Rapidex",
            "Global Suppleceutical Formul.",
            "Refracta",
            "Rejuvi",
            "Kora Healthcare",
            "Vitamins For Life-USA",
            "Gruppo Farmaimpresa s.r.l",
            "FutureWay Nutrition - USA",
            "Boscogen Inc. U.S.A.",
            "Paed Pharm",
            "Hisamitsu Pharma Ltd.",
            "Salviasept",
            "Crab Sinergy S.r.l.",
            "ScarHeal Inc. - USA",
            "Sakura Srl -Italy",
            "Sensilab SA.",
            "Seven Seas Limited",
            "Siddhayu Ayurvedic Research",
            "Biotrading",
            "Chemi Group France",
            "Yasenka",
            "Nutrition Formulators-Pentacar",
            "Vitex Pharma. Australia",
            "Solaray-Health Planet",
            "Sona Nutrition",
            "Sonbaren",
            "Special Kid",
            "Vital Health",
            "LAB FUMOUZE PH",
            "Boots",
            "Rexall Sundown,Inc.",
            "Sundown-Health Planet",
            "Ena Farma Saglik-Turkey",
            "EURO CONNECTION",
            "Sabah salaem Pharmacy",
            "Arab Phar Mfg",
            "Anfarm Pharmaceuticals",
            "Tea Tree Therapy Inc.",
            "Haw Par Healthcare Ltd.",
            "Dant Khaitan PH",
            "Egyptian Gp For Pharma",
            "Les Lab Servier",
            "Trq Vitamec",
            "Berna",
            "Elerte Labs",
            "Bio Farmex S.r.l.-Italy",
            "Halal Nutrition Center",
            "Nutrition Green Life Inc.",
            "Trading Point,Group Elite Ph.",
            "LDPSA- Gilbert-France",
            "Dr. Falk Pharma GmbH",
            "Goerlich Pharma -Germany",
            "Walmark",
            "Pharmaluce S.r.l",
            "P&G",
            "Kaz Europa SA",
            "Canada",
            "Pharmadiet, S.L.U. - Spain",
            "Jenasol USA",
            "Salvum Laboratories-Switzerlan",
            "Blithe Health Care Pvt.Ltd.",
            "Quickmed Biotech.",
            "Walter Ritter",
            "Wassen",
            "Medwise Overseas",
            "Xlear Inc.U.S.A",
            "Amino Labs -Belgium",
            "KSPICO",
            "Catalent",
            "Trio Health Care Pvt.Ltd");

        $suppliers = array("GREEN APPLE",
            "Al-Hafiz Trading Est.",
            "Bicco Medical Co.",
            "Your Health Co. for Medicine imports",
            "Alghanim Healthcare Gen.Trad.Co.",
            "LAIKA GEN . CONT .CO",
            "Safwan Trading & Construction Co.",
            "Jassim Al-Wazan Sons & Trad Co.",
            "HAICO INTERNATIONAL COMPANY",
            "Mohammad nasir Al-Hajri & Sons Co.",
            "Hamoud Al-Azmi Gen trad.co",
            "Yiaco Medical co",
            "Mercury For Drugs and Medical Supply",
            "Pharma Life Co.",
            "Ali Abdulwahab Pharmacies Group",
            "SHIFLI GULF TRADING IN DRUGS,EQUIPMENTS",
            "Boushahri Group Medical Company",
            "Hamad Saleh Al Homazi Grandsons Ph. Co",
            "KUWAIT D.C.GEN.TRAD.CO.",
            "Al-Mojil Drug Co.",
            "Al-Maseela Pharmaceutical Co.",
            "Local Supplier Cash Pharmacies",
            "Total Future Company",
            "Al-Ammar Int. Tra.& Cont. Co",
            "Alpha Care Adavnced General Treading Co.",
            "Al-Mufid Pharmaceutical Co.",
            "Central Circle company",
            "Issac General Trading & contracting co",
            "3 M D PHARMA",
            "GENOA GENERAL TRADING.CO",
            "HEALTH LINE",
            "ADVANCED TECHNOLOGY CO",
            "Barayah Universal Medical Company",
            "MKA CURE FOR DRUGS AND MEDICAL SUPPLY",
            "DAR Al MAALI MEDICAL CO.",
            "Gulf Care Trading Co",
            "Mohammad Amin Abdul Khader Behbehani Co.",
            "SHIFLI GULF GENERAL TRAD&CONT.",
            "Othea Medical Eye Com.",
            "Italia Nuova Medical",
            "INTERNATIONAI PHARMACE GROUP",
            "BIO HEALTH PLUS FOR GENERAL TRADING CO.",
            "Exclusive trading company",
            "UNITED PHARMA CO.",
            "Al- Thouq Nations General Trading & Con.",
            "Advanced Care Med.Equip.&Supp.Co.",
            "Omega Medical Company",
            "Middel East Medical Services Co",
            "DUNIA MEDICAL & TECH.EQUIP.CO",
            "Badar Alsultan Bros & Co.",
            "Warba Medical Supplies Co.",
            "Nawahill Tradding Co.",
            "Mareen Group Co.",
            "Wahran Trading Co.",
            "LAVENIR MEDICAL",
            "Nabea Al Khair Gen.Trd",
            "Hadi Pharmacy Co.",
            "Future Pharma",
            "CURE UNITED TRADING CO.",
            "IBN AL-NAPHIS Co.",
            "AL ROUBA INTERNATIONAL GEN.TRAD.CO.",
            "Dina Health Food Company",
            "AL-ANSAF AL-KHALIJYA GEN.TRAD.CO",
            "Hagag Medical Company",
            "Soft Medical For Pharmaceuticals & Medic",
            "Global Activity General Trading Co.",
            "Gulf Food General Trading For Foodstuff",
            "Medical Health For Drug & Medical Co.",
            "KMA INTERNATIONAL GENERAL TRADING",
            "JC Care Gen & Trd Co.",
            "Bou Shahree Trading Group",
            "Balsam Gulf Tariding",
            "ARWAD REGIONALCO. FOR IMPORT EXPORT",
            "Enervit Tradding Co.",
            "Palastin Pharmacy",
            "Mag Gen Trad & Cont co",
            "Best Remedy Company W.L.L",
            "Pharmadex Pharmaceutical & Medical",
            "Pentacare",
            "Al Batrous",
            "Sour Alsain Arab International General",
            "Pharmazone General Trading Co.",
            "Philo pharma for Import and export",
            "Biomedix Medical Group",
            "WellGreen General Trade Co.",
            "Xidrogen General Trading Co. W.L.L.",
            "AMISYA EST.for genral trading",
            "DELTAmed",
            "GHAZI ALABDUL RAZZAK GEN.TRD.CONT.CO.",
            "Modern Pharma",
            "The Healthy Way",
            "Abdul Rahman Albaser Zaid Al-Kazmi Co.",
            "Al-Amin Medical Instruments Co.",
            "Synergy Health",
            "PHARMACY WAREHOUSE",
            "HEALTH ADDRESS",
            "Alpha gulf trading company",
            "Perfect Life Co.",
            "Fahad ALFahad Medical Co.",
            "Bama pharma co.",
            "Kuwait - Egypt Co. for Hospital Con. & A",
            "Hassan Optical Co.",
            "Corner Stone For Import & Export",
            "Total Care General Trading Co.",
            "Multi Business Vision Gen.Trad.Co.",
            "Health Planet Co. Food Supplement",
            "ADVANCED SYSTEMS CO",
            "UNION TRADING CO.",
            "GREEN APPLE .",
            "Al-Hafiz Trading Est.");

        $brandInfo = $this->_attributeFactory->getCollection()
            ->addFieldToFilter('attribute_code', ['eq' => "brand"])
            ->getFirstItem();
        $supplierInfo = $this->_attributeFactory->getCollection()
            ->addFieldToFilter('attribute_code', ['eq' => "supplier"])
            ->getFirstItem();
        // options = 190
        // dropdown 437
        //result = 252

        //print_r(count($this->getOptions()));
        //die();

        $labelOptions = $this->convertArray($this->getOptions());

        $result = array_diff($suppliers, $labelOptions);

        $option = array();
        $option['attribute_id'] = $supplierInfo->getAttributeId();

        $stores = $this->getAllStores();

        foreach ($result as $key => $value) {
            $option['value'][$value][0] = $value;
            foreach ($stores as $key1 => $value1) {
                $option['value'][$value][$key1] = $value;
            }
        }

        $eavSetup = $this->_eavSetupFactory->create();
        $eavSetup->addAttributeOption($option);
    }

    function getAllStores()
    {
        $stores = $this->_storeManager->getStores();
        $storeArray[0] = "All Store Views";

        foreach ($stores as $store) {
            $storeArray[$store->getId()] = $store->getName();
        }
        return $storeArray;
    }

    public function getOptions()
    {
        $attribute = $this->eavConfig->getAttribute('catalog_product', 'supplier');
        return $options = $attribute->getSource()->getAllOptions();
    }

    public function convertArray(array $options)
    {
        $values = array();
        foreach ($options as $manufacturerOption) {
            //$manufacturerOption->getValue();  // Valu
            $values[] = $manufacturerOption['label'];  // Label

        }
        return $values;
    }
}